## this workflow is used to publish dia-agents-baseservice to npmjs.com
## Trigger condition:
## 1. create a branch named `release/agents-baseservice`
## 2. create a new release from `release/agents-baseservice`
name: Publish Base Service
on:
  release:
    types:
      - published

jobs:
  build:
    # only trigger when branch is `release/agents-basesevice`
    if: ${{ github.ref == 'refs/heads/release/agents-basesevice' }}
    runs-on: ubuntu-latest
    # env:
    #   working-directory: ./dia-agents-baseservice
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.1.0
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.2
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - name: Install node_modules
        run: git status && pwd && ls && yarn install
        working-directory: dia-agents-baseservice
      - name: Publish node_module
        run: git status && pwd && ls && npm publish
        working-directory: dia-agents-baseservice
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
