name: Build/Release

on:
  release:
    types:
      - published
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  release_headless_agent:
    name: Push Headless Agent Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.1.0
        with:
          submodules: true
      - name: Navigate to dia-agents-headless folder and List files
        run: cd ./dia-agents-headless && ls
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: munew/headless-agent
          tag_with_ref: true
          path: ./dia-agents-headless
  
  # release_desktop_app:
  #   # only trigger when it is `release/bitspider` branch
  #   # if: github.ref == 'refs/heads/release/bitspider'
  #   runs-on: ${{ matrix.os }}

  #   # Platforms to build on/for
  #   strategy:
  #     matrix:
  #       os: [macos-latest, windows-latest, ubuntu-latest]
    
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2.1.0
  #       with:
  #         submodules: true
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1.4.2
  #       with:
  #         node-version: "12.x"
  #         registry-url: https://registry.npmjs.org/
  #     - name: Install node_modules
  #       run: ls && yarn install
  #     - name: Build
  #       run: npm run build-electron
  #     - name: List generate files
  #       run: cd ./dia-electron/out && ls
  #     - name: Get Release
  #       id: get_release
  #       uses: bruceadams/get-release@v1.2.0
  #     - name: Upload Release Asset
  #       id: upload-release-asset 
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ steps.get_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
  #         asset_path: ./dia-electron/out/munew.zip
  #         asset_name: 'munew-${{ matrix.os }}.zip'
  #         asset_content_type: application/zip

  createPR:
    needs: release_headless_agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.1.0
        with:
          submodules: true
      - name: Get release version
        run: |
          VERSION=${GITHUB_REF##*/v}
          echo "::set-env name=VERSION::${GITHUB_REF##*/v}"
      - name: Create Pull Request to `master`
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "release/v${{env.VERSION}}"        # If blank, default: triggered branch
          destination_branch: "master"                      # If blank, default: master
          pr_title: "Merge to master - ${{env.VERSION}}"              # Title of pull request
          pr_body: ":crown: successfully publish ${{env.VERSION}}. Pulling release/v${{env.VERSION}} into master"                                      # Full markdown support, requires pr_title to be set
          pr_reviewer: "neoskx"                         # Comma-separated list (no spaces)
          pr_assignee: "neoskx"                         # Comma-separated list (no spaces)
          pr_label: "release"                               # Comma-separated list (no spaces)
          # pr_draft: true                                    # Creates pull request as draft
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request to `develop`
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "release/v${{env.VERSION}}"        # If blank, default: triggered branch
          destination_branch: "develop"                      # If blank, default: master
          pr_title: "Merge to develop - ${{env.VERSION}}"              # Title of pull request
          pr_body: ":crown: successfully publish ${{env.VERSION}}. Pulling release/v${{env.VERSION}} into develop"                                      # Full markdown support, requires pr_title to be set
          pr_reviewer: "neoskx"                         # Comma-separated list (no spaces)
          pr_assignee: "neoskx"                         # Comma-separated list (no spaces)
          pr_label: "release"                               # Comma-separated list (no spaces)
          # pr_draft: true                                    # Creates pull request as draft
          github_token: ${{ secrets.GITHUB_TOKEN }}